version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DATABASE_URL: postgresql://HiveSpace:HiveSpace@db:5432/HiveSpace

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: HiveSpace
      POSTGRES_USER: HiveSpace
      POSTGRES_DB: HiveSpace

volumes:
  postgres-data:
